apiVersion: v1
kind: Service
metadata:
  name: ghost
  labels:
    app: ghost
    component: frontend

spec:
  selector:
    app: ghost
    component: frontend

  ports:
    - name: web
      port: 2368
      protocol: TCP
      targetPort: 2368